package jamiebalfour.zide.languages;
import jamiebalfour.codeeditor.CodeEditorViewFX;
import jamiebalfour.codeeditor.CodeSyntaxModel;
import java.util.Set;
public final class JsonLanguage extends LanguageSupport {
  public record Issue(int line, int column, String message) { }
  public JsonLanguage(jamiebalfour.zide.editor.ZIDEEditor ignored) { super("json", "JSON", Set.of("json", "jsonc")); }
  @Override public void configure(CodeEditorViewFX editor) { editor.setLineCommentMarkers("//"); editor.setBlockCommentMarkers("/*", "*/"); editor.setQuoteDelimiters("\""); editor.setVariableDelimiters(""); editor.setContextSeparator(""); editor.clearKeywords(); editor.clearContextualKeywords(); editor.clearAutoCompleteItems(); for (String keyword : java.util.List.of("true", "false")) { editor.addKeyword(keyword, CodeSyntaxModel.Style.BOOLEAN); editor.addAutoCompleteItem(keyword, CodeEditorViewFX.AutoCompleteItemType.Keyword); } editor.addKeyword("null", CodeSyntaxModel.Style.NULL); editor.addAutoCompleteItem("null", CodeEditorViewFX.AutoCompleteItemType.Keyword); for (String structural : java.util.List.of("object", "array", "string", "number", "boolean", "null")) editor.addAutoCompleteItem(structural, CodeEditorViewFX.AutoCompleteItemType.Type); }
  public static java.util.List<Issue> validate(String source) { try { new Parser(source == null ? "" : source).document(); return java.util.List.of(); } catch (Failure e) { return java.util.List.of(new Issue(e.line, e.column, e.getMessage())); } }
  private static final class Failure extends Exception { final int line; final int column; Failure(int line, int column, String message) { super(message); this.line = line; this.column = column; } }
  private static final class Parser { final String s; int p; Parser(String s) { this.s=s; } void document() throws Failure { ws(); value(); ws(); if (p<s.length()) fail("Unexpected text after JSON value."); } void value() throws Failure { ws(); if(p>=s.length()) fail("Expected a JSON value."); char c=s.charAt(p); if(c=='{') object(); else if(c=='[') array(); else if(c=='\"') string(); else if(c=='-'||Character.isDigit(c)) number(); else if(s.startsWith("true",p)) p+=4; else if(s.startsWith("false",p)) p+=5; else if(s.startsWith("null",p)) p+=4; else fail("Invalid JSON value."); } void object() throws Failure { p++; ws(); if(peek('}')){p++;return;} while(true){ ws(); if(!peek('"')) fail("JSON object keys must be strings."); string(); ws(); expect(':'); value(); ws(); if(peek('}')){p++;return;} expect(','); } } void array() throws Failure { p++; ws(); if(peek(']')){p++;return;} while(true){ value(); ws(); if(peek(']')){p++;return;} expect(','); } } void string() throws Failure { p++; while(p<s.length()){ char c=s.charAt(p++); if(c=='\"') return; if(c=='\\'){ if(p>=s.length()) fail("Unterminated escape sequence."); p++; } else if(c<' ') fail("Control characters are not valid in JSON strings."); } fail("Unterminated JSON string."); } void number() throws Failure { int start=p; if(peek('-'))p++; if(p>=s.length()||!Character.isDigit(s.charAt(p))) fail("Invalid JSON number."); if(s.charAt(p)=='0')p++; else while(p<s.length()&&Character.isDigit(s.charAt(p)))p++; if(peek('.')){p++;int f=p;while(p<s.length()&&Character.isDigit(s.charAt(p)))p++;if(f==p)fail("Expected digits after decimal point.");} if(peek('e')||peek('E')){p++;if(peek('+')||peek('-'))p++;int e=p;while(p<s.length()&&Character.isDigit(s.charAt(p)))p++;if(e==p)fail("Expected exponent digits.");} if(start==p)fail("Invalid JSON number."); } void ws(){while(p<s.length()&&Character.isWhitespace(s.charAt(p)))p++;} void expect(char c)throws Failure{if(!peek(c))fail("Expected '"+c+"'.");p++;} boolean peek(char c){return p<s.length()&&s.charAt(p)==c;} void fail(String m)throws Failure{int line=1,col=1;for(int i=0;i<p&&i<s.length();i++){if(s.charAt(i)=='\n'){line++;col=1;}else col++;}throw new Failure(line,col,m);} }
}
